prophet:
  ontology-id: ont_commerce_local
  compatibility-profile:
    strict-enums: false
  actions:
    base-path: /actions
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
